# Generated by Django 2.0 on 2017-12-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0003_auto_20171220_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrower',
            new_name='user',
        ),
    ]
