# Generated by Django 2.0 on 2017-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/html.png', upload_to='media'),
        ),
    ]
