# Generated by Django 2.0 on 2017-12-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0007_auto_20171221_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
    ]
