# Generated by Django 2.0 on 2017-12-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
