# Generated by Django 2.0 on 2017-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0010_auto_20171221_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='media/files', upload_to='media/files'),
        ),
    ]
