# Generated by Django 2.0 on 2017-12-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0011_auto_20171221_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
