# Generated by Django 2.0 on 2018-01-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0014_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
