# Generated by Django 2.0 on 2018-01-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBook', '0015_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
